Size.create!(size_name:'XXS以下', size_tag:'1')
Size.create!(size_name:'XS(SS)', size_tag:1)
Size.create!(size_name:'S', size_tag:1)
Size.create!(size_name:'M', size_tag:1)
Size.create!(size_name:'L', size_tag:1)
Size.create!(size_name:'XL(LL)', size_tag:1)
Size.create!(size_name:'2XL(3L)', size_tag:1)
Size.create!(size_name:'3XL(4L)', size_tag:1)
Size.create!(size_name:'4XL(5L)以上', size_tag:1)
Size.create!(size_name:'FREE SIZE', size_tag:1)